export enum CardType {
  ALLERGIES = 'allergies',
  APPOINTMENTS = 'appointments',
  ATTACHMENTS = 'attachments',
  CONDITIONS = 'conditions',
  HOSPITALIZATIONS = 'hospitalizations',
  ID_CARD = 'id_card',
  LAB_WORK = 'lab_work',
  MEDICATIONS = 'medications',
  NOTES = 'notes',
  PRACTITIONERS = 'practitioners',
  PROCEDURES = 'procedures',
  QUESTIONS = 'questions',
  VACCINATIONS = 'vaccinations',
}
