export enum Sex {
  MALE = 'Male',
  FEMALE = 'Female',
}

export enum Pronouns {
  HE = 'He/him',
  SHE = 'She/her',
}

export enum BloodType {
  A_POSITIVE = 'A Positive',
  A_NEGATIVE = 'A Negative',
  B_POSITIVE = 'B Positive',
  B_NEGATIVE = 'B Negative',
  AB_POSITIVE = 'AB Positive',
  AB_NEGATIVE = 'AB Negative',
  O_POSITIVE = 'O Positive',
  O_NEGATIVE = 'O Negative',
  UNKNOWN = 'Unknown',
}

export enum SpecialtyType {
  AddictionSpecialistSponsor = 'Addiction Specialist/Sponsor',
  AllergyImmunologist = 'Allergy & Immunologist',
  Anesthesiologist = 'Anesthesiologist',
  BehavioralTherapist = 'Behavioral Therapist',
  BirthCoachDoula = 'Birth Coach (Doula)',
  Cardiologist = 'Cardiologist',
  Chiropractor = 'Chiropractor',
  ColonRectalSurgeon = 'Colon & Rectal Surgeon',
  Counselor = 'Counselor',
  CriticalCareMedicineSpecialist = 'Critical Care Medicine Specialist',
  Dentist = 'Dentist',
  Dermatologist = 'Dermatologist',
  EmergencyMedicine = 'Emergency Medicine',
  Endocrinologist = 'Endocrinologist',
  FamilyMedicine = 'Family Medicine',
  Gastroenterologist = 'Gastroenterologist',
  Geneticist = 'Geneticist',
  GeriatricMedicineSpecialist = 'Geriatric Medicine Specialist',
  HealthCoach = 'Health Coach',
  Hematologist = 'Hematologist',
  HomeCareRegisteredNurse = 'Home Care Registered Nurse',
  HospicePalliativeSpecialist = 'Hospice and Palliative Specialist',
  InfectiousDiseaseSpecialist = 'Infectious Disease Specialist',
  InternalMedicine = 'Internal Medicine',
  LactationSpecialist = 'Lactation Specialist',
  LicensedPracticalNurse = 'Licensed Practical Nurse (LPN)',
  MassageTherapist = 'Massage Therapist',
  Nephrologist = 'Nephrologist',
  Neurologist = 'Neurologist',
  NuclearMedicine = 'Nuclear Medicine',
  NursePractitioner = 'Nurse Practitioner (NP)',
  Nutritionist = 'Nutritionist',
  ObstetricianGynecologist = 'Obstetrician & Gynecologist (OB/GYN)',
  Oncologist = 'Oncologist',
  Ophthalmologist = 'Ophthalmologist',
  Orthodontist = 'Orthodontist',
  OrthopedicSurgeon = 'Orthopedic Surgeon',
  Osteopath = 'Osteopath',
  OtherDoctor = 'Other Doctor',
  OtherNurse = 'Other Nurse',
  OtolaryngologistENT = 'Otolaryngologist (ENT)',
  Pathologist = 'Pathologist',
  Pediatrician = 'Pediatrician',
  Periodontist = 'Periodontist',
  PhysicalMedicineRehabilitation = 'Physical Medicine and Rehabilitation',
  PhysicalTherapist = 'Physical Therapist',
  PlasticSurgeon = 'Plastic Surgeon',
  Podiatrist = 'Podiatrist',
  PreventiveMedicine = 'Preventive Medicine',
  PsychiatricNursePractitioner = 'Psychiatric Nurse Practitioner',
  PsychiatricPA = 'Psychiatric PA',
  Psychiatrist = 'Psychiatrist',
  Psychologist = 'Psychologist',
  Pulmonologist = 'Pulmonologist',
  Radiologist = 'Radiologist',
  RegisteredNurse = 'Registered Nurse (RN)',
  Rheumatologist = 'Rheumatologist',
  SleepSpecialist = 'Sleep Specialist',
  SpeechTherapist = 'Speech Therapist',
  SportsMedicineSpecialist = 'Sports Medicine Specialist',
  Surgeon = 'Surgeon',
  SurgicalAssistantRegisteredNurse = 'Surgical Assistant Registered Nurse',
  Therapist = 'Therapist (LCSW, LPC, LMFT)',
  Urologist = 'Urologist',
}

export enum AllergyType {
  FOOD = 'Food',
  MEDICATION = 'Medication',
  OTHER = 'Other',
}

export enum AllergySeverity {
  MILD = 'Mild',
  MODERATE = 'Moderate',
  SEVERE = 'Severe',
}
